production:
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: postgresql
  database: numerology_development
  pool: 5
  host: localhost
  username: postgres
  password: 12345

test:
  adapter: postgresql
  database: numerology_test
  pool: 5
  host: localhost
  username: postgres
  password: 12345
